-- ZD.TechLab estructura MySQL
CREATE DATABASE IF NOT EXISTS zdtechlab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE zdtechlab;
CREATE TABLE IF NOT EXISTS usuarios(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(150) NOT NULL UNIQUE,
clave_hash VARCHAR(255) NOT NULL,
rol ENUM('administrador','vendedor','consultor') NOT NULL DEFAULT 'vendedor',
activo TINYINT NOT NULL DEFAULT 1,
bloqueado_hasta DATETIME NULL,
creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX idx_correo(correo)
);
CREATE TABLE IF NOT EXISTS intentos_acceso(
id INT AUTO_INCREMENT PRIMARY KEY,
correo VARCHAR(150) NOT NULL,
exito TINYINT NOT NULL,
fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ip VARCHAR(45)
);
CREATE TABLE IF NOT EXISTS categorias(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(80) NOT NULL UNIQUE,
descripcion VARCHAR(200),
activo TINYINT NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS productos(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(120) NOT NULL,
categoria_id INT NOT NULL,
precio DECIMAL(12,2) NOT NULL,
stock INT NOT NULL DEFAULT 0,
stock_minimo INT NOT NULL DEFAULT 5,
activo TINYINT NOT NULL DEFAULT 1,
creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE RESTRICT,
INDEX idx_prod_nombre(nombre), INDEX idx_prod_activo(activo)
);
CREATE TABLE IF NOT EXISTS clientes(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
documento VARCHAR(30) NOT NULL UNIQUE,
correo VARCHAR(150),
telefono VARCHAR(30),
activo TINYINT NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS pedidos(
id INT AUTO_INCREMENT PRIMARY KEY,
cliente_id INT NOT NULL,
fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
total DECIMAL(12,2) NOT NULL DEFAULT 0,
estado VARCHAR(20) NOT NULL DEFAULT 'confirmado',
FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT,
INDEX idx_ped_fecha(fecha)
);
CREATE TABLE IF NOT EXISTS detalle_pedido(
id INT AUTO_INCREMENT PRIMARY KEY,
pedido_id INT NOT NULL,
producto_id INT NOT NULL,
cantidad INT NOT NULL,
precio_unitario DECIMAL(12,2) NOT NULL,
FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE RESTRICT
);
